# Generated by Django 5.2.1 on 2025-06-09 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corevolthrm', '0022_merge_20250606_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('teams', models.ManyToManyField(blank=True, null=True, related_name='prteams', to='corevolthrm.teamname')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
    ]
