# Generated by Django 5.2.1 on 2025-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0022_merge_20250606_1727'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='corevolthrm.teamname'),
        ),
    ]
