# Generated by Django 5.2.1 on 2025-06-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0020_remove_timesheetdetails_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Team (department) to which the employee belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='corevolthrm.teamname'),
        ),
    ]
