# Generated by Django 5.2.1 on 2025-06-11 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0024_asset_assetcategory_delete_itasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=100)),
                ('assetId', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Repair', 'In Repair'), ('Retired', 'Retired'), ('Lost', 'Lost')], default='Available', max_length=50)),
                ('assignedDate', models.DateField(blank=True, null=True)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
