# Generated by Django 5.2.1 on 2025-06-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0025_assetlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_list', to='corevolthrm.assetcategory'),
        ),
    ]
