# Generated by Django 5.2.1 on 2025-06-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0026_assetlist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlist',
            name='category',
        ),
        migrations.AddField(
            model_name='assetlist',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='corevolthrm.asset'),
        ),
    ]
