# Generated by Django 5.2.1 on 2025-06-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0027_remove_assetlist_category_assetlist_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='corevolthrm.employee'),
        ),
    ]
