# Generated by Django 5.2.1 on 2025-06-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0029_alter_assetlist_assignedto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedAsset',
        ),
    ]
