# Generated by Django 5.2.1 on 2025-06-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0030_delete_assignedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corevolthrm.assetcategory'),
        ),
    ]
