# Generated by Django 5.2.1 on 2025-07-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corevolthrm', '0027_alter_employee_user'),
        ('corevolthrm', '0032_remove_assetrequest_category_assetrequest_asset_type'),
    ]

    operations = [
    ]
